### ISSUE TITLE
Needs more documentation

### ISSUE THREAD

**Issue by Ducksss** [ZeInhumane/fuck#1]
Dear @ZeInhumane ,

Hey, I was trying to use this repository, but it seems to be lacking any readme or /docs links and I can't get started on it.

Thanks!

**Comment by ZeInhumane** [comment]
Hi, thanks for your comment @Ducksss. Issue resolved in e15d91c. Marking this as resolved. 
Happy contributing!

**Comment by Ducksss** [comment]
Thanks!
